// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGUVYy9zpc9dyAt0jzHCJnbN8xbL6rV_k',
    appId: '1:387961994683:web:542f5857daf5f20734d89e',
    messagingSenderId: '387961994683',
    projectId: 'todolist-c6e7c',
    authDomain: 'todolist-c6e7c.firebaseapp.com',
    storageBucket: 'todolist-c6e7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5xygS-fbG8ilwHmmCJyYroCzJCdoMlGk',
    appId: '1:387961994683:android:72b06d813e4a78d234d89e',
    messagingSenderId: '387961994683',
    projectId: 'todolist-c6e7c',
    storageBucket: 'todolist-c6e7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8labKVrMwY2BYlSijiVu2Z4n86dzkf3Y',
    appId: '1:387961994683:ios:61380dc67952ac2034d89e',
    messagingSenderId: '387961994683',
    projectId: 'todolist-c6e7c',
    storageBucket: 'todolist-c6e7c.appspot.com',
    iosBundleId: 'com.example.todoListG9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8labKVrMwY2BYlSijiVu2Z4n86dzkf3Y',
    appId: '1:387961994683:ios:5ebf36db7ff459cd34d89e',
    messagingSenderId: '387961994683',
    projectId: 'todolist-c6e7c',
    storageBucket: 'todolist-c6e7c.appspot.com',
    iosBundleId: 'com.example.todoListG9.RunnerTests',
  );
}
